const imgur = require('imgur');
const querystring = require('querystring');

require('dotenv').config();

imgur.setClientId(process.env.IMGUR_CLIENT_ID);
imgur.setAPIUrl('https://api.imgur.com/3/');

/**
 * Generates a QR code from an ID number using Quickchart's API.
 *
 * @param ID The ID of the equipment item
 * @return The URL to the image (QR code).
 */
exports.generateQrCode = (id) => {
  const query = {
    text: encodeURIComponent(id),
    dark: '000000',
    light: 'ffffff',
  };

  return `https://quickchart.io/qr?${querystring.stringify(query)}`;
};

/**
 * Uses Imgur API to upload anon image.
 *
 * @param image The URL to the QR Code generated by generateQrCode()
 * @return The JSON object representing the imgur image upload
 */
exports.uploadToImgur = async (image) => {
  try {
    const json = await imgur.uploadUrl(image);
    return json.data;
  } catch (err) {
    return err;
  }
};
